[package]
name = "serial-multiplexer"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serialport = "4"